### ISSUE TITLE
Emotion labels used in the tasks

### ISSUE THREAD

**Issue by lycheesodaa** [sadat1971/Emotion-Forecasting#1]
Hi! I just chanced upon your paper for emotional forecasting using the IEMOCAP dataset, and found it to be really insightful. Thanks for the great work!

For some context, I too am doing a bit of research on emotional forecasting currently, and was wondering how you managed to cluster the 10 or so existing emotion labels in the original dataset into the four emotions (angry, happy, neutral and sad). From what I understand, it was [this paper](https://emp.engin.umich.edu/wp-content/uploads/sites/67/2022/06/2016_Kim_ICMI.pdf) that introduced the method suggesting a four-dimensional emotional representation of the dataset, but I didn't manage to catch how you implemented it in the codebase you have here.

I understand that the work was done quite a while ago, but I would appreciate any assistance on the matter still! Thank you :)

**Comment by sadat1971** [comment]
I believe, the emotion labels came with the dataset.

**Comment by lycheesodaa** [comment]
Much appreciated! Sorry for the late response, I realized later that you were simply using the four labels amongst the 10, for I thought you were performing a clustering step involving the valence, activation and dominance emotion dimensions.
